In [1]:
import torch

In [2]:
a = [[12,15,13],[11,10,15],[16,23,25]]
A = torch.tensor(a)
A

tensor([[12, 15, 13],
        [11, 10, 15],
        [16, 23, 25]])

Dimension of the tensor

In [3]:
A.ndimension()

2

shape of temsor

In [4]:
A.shape

torch.Size([3, 3])

In [5]:
A.size()

torch.Size([3, 3])

obtain of element in tensor

In [6]:
A.numel()

9

Indexing and Slicing

In [7]:
A

tensor([[12, 15, 13],
        [11, 10, 15],
        [16, 23, 25]])

extraxt element from tensor

In [8]:
A[0][2]

tensor(13)

In [9]:
A[0,2]

tensor(13)

In [10]:
A[0,0:2]

tensor([12, 15])

operation in 2D tensors

In [11]:
x = [[1,0],[0,1]]
y = [[2,1],[1,2]]
X = torch.tensor(x)
Y = torch.tensor(y)

sum

In [12]:
X+Y

tensor([[3, 1],
        [1, 3]])

Scaler multiplication

In [13]:
2*Y

tensor([[4, 2],
        [2, 4]])

Hadamard tensors

In [14]:
X*Y

tensor([[2, 0],
        [0, 2]])

Atrix multiplication

In [15]:
A = torch.tensor([[0,1,1],[1,0,1]])
B = torch.tensor([[1,1],[1,1],[-1,1]])

`Matrix mulriplicatin with torch.mm`

In [16]:
torch.mm(A,B)

tensor([[0, 2],
        [0, 2]])

`Derivative`

In [20]:
x = torch.tensor(2.,requires_grad=True)
y = x**2

For calculating the derivative of y we call `.backward()`

In [21]:
y.backward()

For having a direct derivation of x with the value of 2 we should use `.grad`

In [23]:
x.grad

tensor(4.)

Another example

In [32]:
x = torch.tensor(2.,requires_grad=True)
z = x**2+2*x+1
z.backward()
x.grad

tensor(6.)

`Partial derivatives`

In [36]:
u = torch.tensor(1., requires_grad = True)
v = torch.tensor(2., requires_grad = True)
f = u*v + u**2
f.backward()
v.grad, u.grad

(tensor(1.), tensor(4.))