In [1]:
import torch

In [3]:
a = [[12,15,13],[11,10,15],[16,23,25]]
A = torch.tensor(a)
A

tensor([[12, 15, 13],
        [11, 10, 15],
        [16, 23, 25]])

Dimension of the tensor

In [5]:
A.ndimension()

2

shape of temsor

In [6]:
A.shape

torch.Size([3, 3])

In [7]:
A.size()

torch.Size([3, 3])

obtain of element in tensor

In [8]:
A.numel()

9

Indexing and Slicing

In [9]:
A

tensor([[12, 15, 13],
        [11, 10, 15],
        [16, 23, 25]])

extraxt element from tensor

In [10]:
A[0][2]

tensor(13)

In [11]:
A[0,2]

tensor(13)

In [12]:
A[0,0:2]

tensor([12, 15])

operation in 2D tensors

In [17]:
x = [[1,0],[0,1]]
y = [[2,1],[1,2]]
X = torch.tensor(x)
Y = torch.tensor(y)

sum

In [18]:
X+Y

tensor([[3, 1],
        [1, 3]])

Scaler multiplication

In [19]:
2*Y

tensor([[4, 2],
        [2, 4]])

Hadamard tensors

In [23]:
X*Y

tensor([[2, 0],
        [0, 2]])

Atrix multiplication

In [25]:
A = torch.tensor([[0,1,1],[1,0,1]])
B = torch.tensor([[1,1],[1,1],[-1,1]])

`Matrix mulriplicatin with torch.mm`

In [26]:
torch.mm(A,B)

tensor([[0, 2],
        [0, 2]])